

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-atguigu-dev
server:
  port: 3355

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-atguigu-test
server:
  port: 3355